import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { Icon } from "@/components/icons";
import { Score, StatusPill } from "@/components/ui";
import { jobs } from "@/lib/data";

export default async function JobDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const job = jobs.find((item) => item.id === id); if (!job) notFound();
  return <AppShell><div className="animate-rise pb-20 lg:pb-0">
    <Link href="/jobs" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-[#65716c]"><span className="rotate-180"><Icon name="arrow" className="h-3.5 w-3.5"/></span>返回岗位管理</Link>
    <section className="soft-shadow rounded-2xl border border-[#e4e9e2] bg-white p-5 md:p-7"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div className="flex gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#edf2eb] text-sm font-black text-[#466157]">{job.accent}</span><div><div className="mb-2 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-[-.04em]">{job.role}</h1><StatusPill status={job.status}/></div><p className="text-sm text-[#6f7975]">{job.company} · {job.location} · {job.salary}</p></div></div><button className="rounded-xl bg-[#234e43] px-4 py-2.5 text-xs font-bold text-white">生成定制简历</button></div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><div className="space-y-5"><section className="soft-shadow rounded-2xl border border-[#e4e9e2] bg-white p-6"><div className="flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#6b887c]">AI match report</p><h2 className="mt-2 text-lg font-bold">岗位匹配分析</h2></div><div className="text-right"><span className="text-4xl font-semibold tracking-[-.06em]">{job.score}</span><span className="text-sm text-[#8b9490]"> / 100</span></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#edf0eb]"><div className="h-full rounded-full bg-[#7ca383]" style={{width:`${job.score}%`}}/></div><p className="mt-4 text-sm leading-7 text-[#65706b]">你的 AI 产品落地经验和跨团队协作能力与岗位高度匹配。建议在简历中进一步量化产品增长结果，并补充企业级 Agent 的评估方法。</p></section>
      <section className="soft-shadow rounded-2xl border border-[#e4e9e2] bg-white p-6"><h2 className="text-[15px] font-bold">技能拆解</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">{[["优势匹配",["AI 产品规划","用户研究","数据驱动","跨团队协作"]],["建议补充",["RAG 评估体系","企业 SaaS","英文工作能力"]]].map(([title, items], i)=><div key={title as string}><p className="mb-3 text-xs font-bold text-[#68736e]">{title as string}</p><div className="flex flex-wrap gap-2">{(items as string[]).map(item=><span key={item} className={`rounded-lg px-2.5 py-1.5 text-[11px] font-semibold ${i===0?"bg-[#e7f0e9] text-[#3d6c50]":"bg-[#f7eadf] text-[#8b5e3b]"}`}>{item}</span>)}</div></div>)}</div></section>
      <section className="soft-shadow rounded-2xl border border-[#e4e9e2] bg-white p-6"><h2 className="text-[15px] font-bold">岗位描述</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-[#68736e]">负责 AI 产品从需求洞察、方案设计到上线迭代的完整生命周期；与算法、工程和业务团队协作，推动大模型能力在真实场景中落地。{`\n\n`}我们希望你具备 3 年以上产品经验，对生成式 AI 有持续实践，并能用数据验证产品价值。</p></section></div>
      <aside className="space-y-5"><section className="soft-shadow rounded-2xl border border-[#e4e9e2] bg-white p-5"><h2 className="text-[15px] font-bold">下一步建议</h2><div className="mt-5 space-y-4">{[["优化简历", "突出 2 个 AI 产品的业务结果"],["准备面试", "生成 8 个高频问题与回答框架"],["发起沟通", "基于岗位卖点生成开场白"]].map(([title,desc],i)=><div key={title} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[#e8efdf] text-[10px] font-black text-[#506d45]">{i+1}</span><div><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[11px] leading-5 text-[#7d8783]">{desc}</p></div></div>)}</div></section><section className="rounded-2xl bg-[#d9ef84] p-5"><Icon name="spark" className="h-5 w-5 text-[#234e43]"/><h2 className="mt-4 text-[15px] font-bold text-[#234e43]">让 Agent 继续工作</h2><p className="mt-2 text-xs leading-5 text-[#436358]">创建一个岗位任务，自动完成资料整理、简历建议和面试准备。</p><button className="mt-4 w-full rounded-xl bg-[#234e43] py-2.5 text-xs font-bold text-white">创建 Agent 任务</button></section></aside>
    </div>
  </div></AppShell>;
}
